# Generated by Django 5.2.8 on 2025-11-28 08:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_sharedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 29, 8, 48, 34, 330067, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
